### ISSUE TITLE
Why don't you try to use Flowable as possible?

### ISSUE THREAD

**Issue by yubaokang** [amitshekhariitbhu/RxJava2-Android-Samples#1]

**Comment by amitshekhariitbhu** [comment]
No specific reason . I will try to add this

**Comment by kongnanlive** [comment]
Flowable vs Observer, Which should we use?

**Comment by amitshekhariitbhu** [comment]
Depends on requirement. Flowable handles back pressure

**Comment by nelson1110** [comment]
我觉得还是Observable性能更好一些，但是flowable处理back pressure更方便一些

**Comment by progratient** [comment]
@nelson1110 你好，你看过源码吗？为什么 Observable 性能比 Flowable 好？请赐教。

**Comment by geolo123** [comment]
背压性能问题！




------------------ 原始邮件 ------------------
发件人: "Huajian Jiang";<notifications@github.com>;
发送时间: 2017年10月11日(星期三) 晚上8:34
收件人: "amitshekhariitbhu/RxJava2-Android-Samples"<RxJava2-Android-Samples@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [amitshekhariitbhu/RxJava2-Android-Samples] Why don't you try touse Flowable as possible? (#1)




@nelson1110 你好，你看过源码吗？为什么 Obserevable 性能比 Flowable 好？请赐教。
