### ISSUE TITLE
Simple Real-world app example

### ISSUE THREAD

**Issue by fadzley** [amitshekhariitbhu/RxJava2-Android-Samples#15]
Hi
Great work you have done here. If possible can you include a real-world app example for clearer picture of RXJava2 can do? News feed reader maybe?

Thanks

**Comment by amitshekhariitbhu** [comment]
@fadzley sure we will be adding it soon.

Thanks
Amit Shekhar

**Comment by amitshekhariitbhu** [comment]
@fadzley 
I have added an example for Pagination in RecyclerView for LoadMore Implementation.
https://github.com/amitshekhariitbhu/RxJava2-Android-Samples/blob/master/app/src/main/java/com/rxjava2/android/samples/ui/pagination/PaginationAdapter.java

**Comment by fadzley** [comment]
Cool. Thanks
