### ISSUE TITLE
Course Typo

### ISSUE THREAD

**Issue by progratient** [amitshekhariitbhu/RxJava2-Android-Samples#24]
![qq 20171011153408](https://user-images.githubusercontent.com/12984573/31427582-61487fa4-ae9a-11e7-88ec-128ccba1fc83.png)

I don't known whether it's a typo as the arrow I point ?
I think it is subscriber and not publisher need to be handled，it is right ?

thx

**Comment by amitshekhariitbhu** [comment]
It's correct there is not typo error.

**Comment by progratient** [comment]
@amitshekhariitbhu  I am sorry ，it's my fault to understand .
It's right , the items emitted by publisher is overflow , and the subscriber is too tired and too slow to handle these items.
