### ISSUE TITLE
takeUntil optimized cache and network method and Gson parse model

### ISSUE THREAD

**Issue by alouanemed** [amitshekhariitbhu/RxJava2-Android-Samples#6]
Hey
Thank you for this awesome examples :)

I am trying to implement the optimized cache method using `takeUntil` in my app. I am using a Gson model to parse the JSON response  from the API .
I've been testing several methods but didn't succeed to get it right.am beginner in RxJava .

My code
https://gist.github.com/alouanemed/6b5f4d5d3623ae69331de25c12dd5b98

Thanks :) .

**Comment by amitshekhariitbhu** [comment]
@alouanemed on the first look on your code, your implementation seems fine, anyway, I will check it more deeply and reply you.
